<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.3.0</Version>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <FileVersion>1.0.3.0</FileVersion>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>

	  <ApplicationManifest>app.manifest</ApplicationManifest>

    <NoWarn>MSB3277</NoWarn>

    <ApplicationIcon>notepad.ico</ApplicationIcon>

    <AssemblyTitle>Transparent Notepad</AssemblyTitle>
    <AssemblyDescription>A stealthy, transparent note-taking application designed for privacy during screen sharing.</AssemblyDescription>
    <Company>DebjeetDas</Company>
    <Product>Transparent Notepad</Product>
    <Copyright>Copyright © 2026 DebjeetDas</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
    <Authors>Debjeet</Authors>

    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>

    <!-- Single File & Native DLL Fix -->
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

    <!-- Smallest EXE Size (Requires .NET Desktop Runtime on host PC) -->
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>

    <RepositoryUrl>https://github.com/siliconvalley007/TransparentNotepad</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="notepad.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
  </ItemGroup>
</Project>